import { NestFactory } from '@nestjs/core';
import { MicroserviceOptions, Transport } from '@nestjs/microservices';
import { ConfigService } from '@nestjs/config';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const configService = app.get(ConfigService);

  // Enable CORS for frontend (configurable via env)
  const corsOrigins = configService.get<string>('CORS_ORIGINS');
  app.enableCors({
    origin: corsOrigins
      ? corsOrigins
          .split(',')
          .map((origin) => origin.trim())
          .filter(Boolean)
      : ['http://localhost:3001'], // Default: Next.js dev server
    credentials: true,
  });

  // OpenAPI/Swagger configuration
  const config = new DocumentBuilder()
    .setTitle('FNO Platform API')
    .setDescription(
      'Backend API for simplifying FNO RK (Tax Reporting Forms for the Republic of Kazakhstan) submissions',
    )
    .setVersion('1.0')
    .addBearerAuth()
    .build();

  const document = SwaggerModule.createDocument(app, config);

  SwaggerModule.setup('api/docs', app, document);
  // Swagger UI: /api/docs
  // OpenAPI JSON: /api/docs-json (auto-generated by NestJS)
  // OpenAPI YAML: /api/docs-yaml (auto-generated by NestJS)

  // Connect Kafka microservice (hybrid mode)
  const kafkaBrokers = configService.get<string>('KAFKA_BROKERS');
  if (kafkaBrokers) {
    app.connectMicroservice<MicroserviceOptions>({
      transport: Transport.KAFKA,
      options: {
        client: {
          clientId:
            configService.get<string>('KAFKA_CLIENT_ID') ?? 'fno-platform',
          brokers: kafkaBrokers.split(','),
        },
        consumer: {
          groupId:
            configService.get<string>('KAFKA_CONSUMER_GROUP_ID') ??
            'fno-consumer-group',
        },
      },
    });

    await app.startAllMicroservices().catch((err: Error) => {
      console.warn(
        'Kafka connection failed, running without Kafka:',
        err.message,
      );
    });
  }

  const port = configService.get<number>('PORT') ?? 3000;
  await app.listen(port);
  console.log(`Application is running on: http://localhost:${port}`);
  console.log(`Swagger UI: http://localhost:${port}/api/docs`);
  console.log(`OpenAPI JSON: http://localhost:${port}/api/docs-json`);
}
void bootstrap();
